configura={
    "STATIC_FOLDERS":"static",
    "TEMPLATE_FOLDER":"templates",
    "DEBUG":True,
    "SERVER_NAME":"http://192.168.77.59:5000",
    "PUERTOREST":5000,
    "PUERTOAPP":8000,
    "MODULO":"salud",
    "SMBD":"SQLITE"
}